### ISSUE TITLE
heollo,can you  help me?

### ISSUE THREAD

**Issue by luoshihang5740** [yuwfan/HGN#16]
I have trained the data, but I keep getting this problem when I run train.py：Traceback (most recent call last):
  File "train.py", line 164, in <module>
    start, end, q_type, paras, sents, ents, _, _ = model(batch, return_yp=True)
  File "/home/luoshihang/miniconda3/envs/MRC/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/luoshihang/py_proj/HGN-master/models/HGN.py", line 74, in forward
    input_state, _ = self.ctx_attention(input_state, graph_state, graph_mask.squeeze(-1))
  File "/home/luoshihang/miniconda3/envs/MRC/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/luoshihang/py_proj/HGN-master/models/layers.py", line 343, in forward
    gate_th = torch.tanh(self.input_linear_2(output))
  File "/home/luoshihang/miniconda3/envs/MRC/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/luoshihang/miniconda3/envs/MRC/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/luoshihang/miniconda3/envs/MRC/lib/python3.7/site-packages/apex/amp/wrap.py", line 21, in wrapper
    args[i] = utils.cached_cast(cast_fn, args[i], handle.cache)
  File "/home/luoshihang/miniconda3/envs/MRC/lib/python3.7/site-packages/apex/amp/utils.py", line 97, in cached_cast
    if cached_x.grad_fn.next_functions[1][0].variable is not x:
IndexError: tuple index out of range

**Comment by r-mohammadi** [comment]
@luoshihang5740 you can edit utils.py file in  "/home/luoshihang/miniconda3/envs/MRC/lib/python3.7/site-packages/apex/amp/utils.py"
in line 97 change cached_x.grad_fn.next_functions[1][0] to cached_x.grad_fn.next_functions[0][0] and problem will be solved

**Comment by luoshihang5740** [comment]
Thank you for your help

**Comment by luoshihang5740** [comment]
I have a new issue:Traceback (most recent call last):
  File "train.py", line 49, in <module>
    train_dataloader = helper.train_loader
  File "/home/luoshihang/py_proj/HGN-master/csr_mhqa/data_processing.py", line 475, in train_loader
    return self.DataIterator(*self.load_train(),
  File "/home/luoshihang/py_proj/HGN-master/csr_mhqa/data_processing.py", line 459, in load_train
    return self.train_features, self.train_example_dict, self.train_graphs
  File "/home/luoshihang/py_proj/HGN-master/csr_mhqa/data_processing.py", line 436, in train_example_dict
    self.__train_example_dict__ = {e.qas_id: e for e in self.train_examples}
  File "/home/luoshihang/py_proj/HGN-master/csr_mhqa/data_processing.py", line 417, in train_examples
    return self.__get_or_load__('__train_examples__', self.train_example_file)
  File "/home/luoshihang/py_proj/HGN-master/csr_mhqa/data_processing.py", line 401, in __get_or_load__
    setattr(self, name, pickle.load(fin))
  File "/home/luoshihang/miniconda3/envs/MRC/lib/python3.7/gzip.py", line 307, in peek
    return self._buffer.peek(n)
  File "/home/luoshihang/miniconda3/envs/MRC/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/home/luoshihang/miniconda3/envs/MRC/lib/python3.7/gzip.py", line 493, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

can you help me one more time?  thank you very much
